CREATE TABLE FORNECEDOR (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  cpf_cnpj INTEGER UNSIGNED NULL,
  nome VARCHAR(45) NULL,
  endereco VARCHAR(45) NULL,
  telefone INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);;
